# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/olc-utils',
                'doc_host': 'https://ankurdivekar.github.io',
                'git_url': 'https://github.com/ankurdivekar/olc-utils',
                'lib_path': 'olc_utils'},
  'syms': {'olc_utils.neighborhood': {}}}
